lib/bundle.js

It's a bit brute force, but this fixes #71

Stub to ignore require('sys')

---

bin/nexe
lib/exe.js

This fixes #107, it implements #105, and fixes an unmarked bug with `--python` on *nix operating systems!
Using a PR because it's nice and clean.

Implement io.js support! And a few fixes

---

lib/bundle.js

Such as `//# sourceMappingURL=...`.

Fix a bug caused by last line being a `//` comment

---

.gitignore
lib/bundle.js
lib/exe.js

Provides the means to pass browserify excludes via options to compile.

ISSUE-184: Allow browserify configuration to be passed through to bundler.

---

README.md
lib/exe.js

Hello,
Hope you find this PR useful.
Its purpose is to have a way to set arguments to VCBuild.bat
Thanks
Silvio

makeVCBuildArgs option added

---

README.md
lib/exe.js

This addresses #261 for the master branch (v1.x)

allow custom V8 startup snapshot

---

README.md

This makes the CircleCI badge look more like the other badges

Match CircleCI badge style to other badges

---

issue_template.md

Prompts for useful information when issues are submitted.

chore: add issue template

---

package.json

Note the minimum Node.js engine required

---

src/compiler.ts

Fix minor spelling problem

---

src/steps/shim-fs.ts

In particular with a mind to using serve-static.

Add resources support for createReadStream.

---

package.json

fix: add  pify, source-map and uglify-es in package.json

---

package.json
src/patches/third-party-main.ts

Per our conversation on gitter, @calebboyd.

Patched third-party bootstrapper for Node 4.x

---

src/compiler.ts

Fix Windows PATH setting for Python configuration

---

.circleci/bootstrap.sh
.circleci/config.yml
.circleci/test.sh
circle.yml
package.json

Best to stay with the times, pretty sure they're deprecating the 1.0 format now anyways.
When/If this is merged, please _squash_. CI tests suck because you have to commit a lot.

Use CircleCI 2.0

---

issue_template.md

I find ones following this style tend to be utilized more and not CTRL+A+Backspace'd

feat: slightly better issue template

---

src/patches/index.ts
src/patches/snapshot.ts

Looks like this might have been forgotten.

Include snapshot in patches

---

src/options.ts

Remove legacy option `compress`

Remove legacy compress option

---

src/patches/disable-node-cli.ts

Equivalent to #448.
Also, changed the code to use `$&` for simplification.

fix: support NODE_OPTIONS in newer node versions

---

src/target.ts

fix: arm arch mapping

---

src/fs/patch.ts

This PR support the `options` argument added to `fs.stat`. It currently allow to specify a `bigint` flag to returns stat numeric values as `bigint`.
Documented at https://nodejs.org/api/fs.html#fs_fs_stat_path_options_callback
Currently if the `options` argument is specified the stat function can fail:
```
callback(null, stat);
^
TypeError: callback is not a function
```
https://github.com/nexe/nexe/blob/cc2c5e31fc881726d78fff124b31d9a23f0aaec8/src/fs/patch.ts#L264
`BigInt` is only defined since Node 10.4.0

Support the new fs.stat prototype (an `options` argument was added)

---

src/patches/third-party-main.ts

Adds support for 12.19.1 - the `StartMainThreadExecution` function has been removed (there might be a better way to do this using LoadEnvironment, but this worked and was consistent with the existing code).
None raised as yet - without this 12.19.1 goes into the repl rather than the app code.
Manually tested with 12.16.2 and 12.19.1

Adding support for 12.19.1.

---

package-lock.json
package.json

Fixes #865
Just to ease the push to Nexe I opened this PR :)

fix: update resolve-dependencies to 6.0.5

---

README.md

**What this PR does / why we need it**: Adds a Discord link to our README

docs(README): add discord

---

src/fs/patch.ts
src/patches/third-party-main.ts

Adds support for Node v20.
Fixes #1062
Seems to be working :-)

Add support for node v20.

---

package.json
src/fs/patch.ts

v4 Variant of #1120 
Fixes # #1119

fix(node22): handle new arg order
