- examples/hello-world/build.js
- examples/hello-world/index.js
- lib/bundle.js
- lib/embed.js
- lib/exe.js
Add support for embedded files.
provided an array or resource files to embed nexe will now base64 encode the files into strings in a new module nexeres. From inside your application doing a require('nexeres').keys() will give you back an array of all the embedded files. and require('nexeres').get(fileName) will give you back the given file. 
They fileName is a string match, and to the relative path from the resource root dir. The hello world example has been changed to embed the message.txt file as an example.
I tested this with a web server that added 125 static files as embedded files. Performance was good, but then again total memory foot print was less than 3mb. I would expect things to go bad if you tried to embed say a large video file.
If you still want to run your app as normal …
> Embed files

- lib/bundle.js
This will fix an oversight that caused a bug when forking a child process. The process.argv are not correct for the child proc.
The main process
process.argv[0] = the nexe compiled executable
process.argv[1] = nexe.js
The child process forked from a bundled script should be the same
process.argv[0] = the nexe compiled executable
process.argv[1] = nexe.js
(before this fix, argv[0] == '--child_process', argv[1]=='forkedScript.js')
The child process forked to an external .js file should be
process.argv[0] = the nexe compiled executable
process.argv[1] = theForkedScript.js
(before this fix, argv[0] == '--child_process')
This is consistent, and will allow any node module to always get the running executable by looking at process.argv[0]
> Make process.argv consistent in the child fork case

- lib/bundle.js
Embarrassingly simple fix.  Added .json to the list of extensions to search when a require with no extension is found.  
Resolves #57
Resolves #72
> Support .json extensions in require() resolution

- lib/bundle.js
This fixes #71 better.   It's less hacky, and doesn't require the extra empty file.  This also opens the door for adding user specified exclusions down the line. 
(Like express, which is a honking monster and has been no end of headache to package)
> Lighter weight way to accomplish the exclusion of the sys module

- package.json
Was facing an error while using nexe because console was not added to the list of modules returned by builtins, prior to 1.0.1. This PR updates the builtins dependency to 1.0.1.
Fixes #112
> Updated version of dependency builtins to 1.0.1 ( inclusion of console to the built in module list )

- lib/exe.js
Fixes https://github.com/jaredallard/nexe/issues/134
Removes the possibility of a silent build failure (if the executable has already been compiled)
The error now looks like this:
> Handle build failure

- lib/bundle.js
- lib/exe.js
- package.json
Related pull request https://github.com/tj/commander.js/pull/460
Besides the fix and problems with commander.js I mentioned in #120 , I am trying to proxy browserResolve in `module-deps` to prevent it from adding "browser" field as polyfill (typically `form-data` module as the dependency of `request` module).
Sorry I don't have much time to split these commits. Feel free to let me know if there's something improper.
> proxy browserResolve, fix `child_process.fork` results in bad option, efforts on commander.js compatibility.

- lib/exe.js
example:
"runtime": {
"framework": "nodejs",
"version": "5.0.0",
"ignoreFlags": true,
"nodeConfigureArgs": ["--fully-static"],
"nodeMakeArgs": ["-j","4"]
}
there is no check if those flags change, which means
if they are changed you must rm -rf the temp directory
will probably push a commit that writes a checksum of them
in the node temp directory so it knows when it is invalid, but not surei f that is a good idea
I did not add support for those as `argv` options, because it seems it can be quite confusing what goes where.
Anyway, please consider this pull request as more of a "feature request", and this is just my
hacky way of implementing what I needed.
> add nodeConfigureArgs and nodeMakeArgs from package.json

- lib/exe.js
To enable operation with Node.js 0.10.x
> Make checkThatExecutableExists backwards compatible

- lib/exe.js
This makes my build fails since `pv` is undefined and you try to assign it the `undefined` value. I'm maybe guessing that `pv` should be `py`, but since the variable is not used anywhere after, I think we could safely remove this.
> fix(exe): remove assignation on undefined variable

- lib/exe.js
This fixes "Native module not found" problem when using excluded modules. With this fix nodejs will treat nexe.js same way as one would use --eval parameter. Otherwise nodejs will thead nexe.js as a NativeModule and for that reason it will ignore excluded modules.
Tested with nodejs 5.9.1 on Windows
> Fixes "Native module not found" problem

- lib/bundle.js
Problem - Issue #243 
[b.require(file, opts)](https://github.com/substack/node-browserify#brequirefile-opts)
Use the `expose` property of opts to specify a custom dependency name. `require('./vendor/angular/angular.js', {expose: 'angular'})` enables `require('angular')`
> #243 - hotfix call browserify.require(file, opts)

- bin/nexe
Here a fix to accept absolute paths in command line arguments instead of joining them to process.cwd()
> =fixed toAbsolute for exists check instead of joining blindly

- lib/exe.js
or else in paths such as `C:\target\foo` the `\t` would be replaced by a tab, causing very weird errors.
> startupSnapshot: need to generate python raw strings because of windows paths

- src/compiler.js
Setting the `python` option did not work on Windows for me as I already had the Python 3.x directory path in my `PATH` variable for my normal Python usage.  In order to allow the `python` option to override that, it must be _**prepended**_ to the existing `PATH` value rather than being appended.
> Prepend the Python path for Windows for overriding

- lib/exe.js
Setting the `python` option did not work on Windows for me as I already had the Python 3.x directory path in my `PATH` variable for my normal Python usage.  In order to allow the `python` option to override that, it must be _**prepended**_ to the existing `PATH` value rather than being appended.
Same as previously merged PR #336, except targeting the `V1-EOL` branch.
> Prepend the Python path for Windows for overriding (V1-EOL)

- src/options.ts
Without this, when you run `nexe --help` in a terminal, your shell prompt will be on the same line as `option can be used more than once`.
> Add newline to end of command line help text

- src/compiler.ts
- src/logger.ts
Personally, I find it useful to see the build process output (I was debugging some issues initially, but just generally useful to know what's happening).
This is just a simple PR to show the external process output when the log level is set to verbose.
I'd initially considered adding a `trace` type log level, but my current thinking is that keeping the number of log levels small is nicer, and if a user asks for `verbose` then getting this output is useful. It was also just simpler as a "thoughts on doing this?" PR :-)
> Show process output when loglevel is verbose.

- src/compiler.ts
The github token is only needed for the API access and will confuse amazon S3 when it is passed to the download:
```
<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>token herebesecrettoken</ArgumentValue><RequestId>7CCDB87CF1347C29</RequestId><HostId>xyyeVP5ImwDePFMXAZheNYLnXQBsVCka4U6KLWKCjynHNpQZxzfBdl4sRfUbORSul8c8YNwux8w=</HostId></Error>
```
Refs #425
> Remove the ghToken for binary download

- src/patches/node-rc.ts
Hi there. I've got an issue with compiling nodejs and i started to dig in and found out that the regex in node.rc patch is invalid.
https://github.com/nexe/nexe/blob/719804eb2fc695d388d5b15cf98a36618368c6a1/src/patches/node-rc.ts#L16
It matches the character `,` literally zero or unlimited times.
And the result was `VALUE "CompanyName", "New company" "Node.js"`
A small pull request with a tiiinyy fix.
> Fix regex in node.rc patch

- README.md
- src/patches/disable-node-cli.ts
The current `disable-node-cli` patch disables all argument parsing.
This patch changes that patch to disable the argv parsing, but allow the NODE_OPTIONS parsing (is_env is true in that case).
This can be useful to allow debugging, eg `NODE_OPTIONS=--inspect ./out.nexe`.
The NODE_OPTIONS support can be disabled with the `--without-node-options` configure flag.
Happy to make any changes :-)
> Don't short circuit NODE_OPTIONS.

- src/compiler.ts
fixes #474
amends #476
related to nodejs/node#20605
> fix: case-sensitive windows PATH setting for python configuration

- src/steps/shim-fs.ts
Fixes #485.
The send module (via serve-static, via express.static) calls stat on a file before attempting to send it.
The manifest is not setup in the stat functions so the bundled file is not found.
> Ensure setupManifest is called for stat functions.

- README.md
To avoid confusion regarding the resource glob string, all examples i the readme should be in strings.
> Resource should always we a glob string.

- src/steps/shim.ts
This will preserve backslashes on windows instead of producing code like:
```js
require.resolve("mydirundle.js")
```
where the path was actually `mydir\bundle.js`
> Stringify `compiler.entrypoint` in shims

- package-lock.json
- src/compiler.ts
This fixes #540 by implementing a way to know whether the binary should be recompiled or not, based on the last modified timestamps of the snapshot file to embed in the binary.
I tested this on my project that has 2 build stages (snapshot doesn't change from 1st to 2nd stage) and it indeed builds a binary the first time but not the 2nd time.
> Invalidate binary cache when snapshot file changes

- src/fs/patch.ts
Just a small optimisation, if of interest :-) It also makes the code read a little cleaner, imo.
(Previously, if logging was disabled then log would be set to noop on first invocation; but if it was enabled then the if check would be processed every time.)
As another thought, I believe `if(/\bnexe:require\b/i.test(process.env.DEBUG))` is a tempting alternative to the if statement. It avoids the need for the `|| ''` because the test returns false if process.env.DEBUG is undefined; it also avoids the need to toLowerCase the string, and it also avoids clashing with longer strings that match (alas, in this instance that's not a big concern; but for example the existing code would match `mylognexe:require`, however I don't believe that to be "correct").
Just a thought, feel free to entirely …
> Avoid checking DEBUG every log, if set.

- src/fs/patch.ts
Currently the `stat` stub functionality fails with the `esm` module because the `esm` module is using `Reflect` to call some stat functions, eg `isFile`. I created a little demo script to show the functionality and the error. This branch fixes that by ensuring the prototype is correct for the stats stub return objects.
tmp.js
const fs = require('fs')
const fileStat = fs.statSync('./tmp.js')
console.log('--- File ---')
console.log('isFile: ', fileStat.isFile())
console.log('Reflect isFile: ', Reflect.apply(fs.Stats.prototype.isFile, fileStat, []))
console.log('isDirectory: ', fileStat.isDirectory())
console.log('Reflect isDirectory: ', Reflect.apply(fs.Stats.prototype.isDirectory, fileStat, []))
const dirStat = fs.statSync('./src')
console.log('')
console.log('--- Directory ---') …
> Stats prototype

- src/patches/snapshot.ts
These changed from e.g. `embed_script` to `v8_embed_script` recently, and I was seeing that my binary didn't contain the snapshot.
> Fix snapshot variable names after Node 11

- src/fs/patch.ts
Fixes https://github.com/nexe/nexe/issues/659
After packaging, running the following command on Windows
```
c:\MyDir\MyApp.exe
```
(note the lowercase drive letter)
caused the following exception:
```
internal/modules/cjs/loader.js:775
throw err;
^
Error: Cannot find module 'c:\MyDir\dist\bundle.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
at Function.Module._load (internal/modules/cjs/loader.js:677:27)
at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
at internal/main/run_main_module.js:17:11 {
code: 'MODULE_NOT_FOUND',
requireStack: []
```
Summary of fixes:
- winPath was not upcasing drive letters of namespace-prefixed keys
- internalModuleReadFile and internalModuleStat were not normalizing keys before checking the manifest for …
> fix: two windows fs patch bugs

- src/steps/resource.ts
Resources were not being picked up on Windows when specified with a backslash e.g, `mydir\myfile.ffs`
This is due to [this issue at globby](https://github.com/sindresorhus/globby/issues/127) which is in turn due to [this change at fast-glob](https://github.com/mrmlnc/fast-glob#pattern-syntax).
Workaround in this PR: converting all backslashes to forward-slashes.
> fix: resources not being included on Windows

- src/patches/disable-node-cli.ts
Fixes #739.
ProcessGlobalArgs was changed to be multiline. This can be seen with 12.16.1 now.
Fixes #739.
I tried this manually with 12.16.1 and 11.7.0.
11.7.0: `const int exit_code = 0;/*ProcessGlobalArgs(argv, exec_argv, errors, false);*/`
12.16.1:
```
const int exit_code = 0;/*ProcessGlobalArgs(argv,
exec_argv,
errors,
kDisallowedInEnvironment);*/
```
> Handle multiline ProcessGlobalArgs change.

- src/patches/third-party-main.ts
Removing an assertion added in [PR30349](https://github.com/nodejs/node/pull/30349).
No issue created previously, but the error output with 12.16.1 is:
```
internal/assert.js:14
throw new ERR_INTERNAL_ASSERTION(message);
^
Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues
at assert (internal/assert.js:14:11)
at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:129:3)
at internal/main/run_main_module.js:7:1 {
code: 'ERR_INTERNAL_ASSERTION'
}
```
_I'm not sure if there's a better way to deal with the upstream change, but …
> Remove hasLoadedAnyUserCJSModule assertion to fix startup.

- README.md
- src/compiler.ts
- src/options.ts
- test/options.spec.ts
- Removes `--asset` option, which was not working as designed.
- Adds `--remote` option, which covers the same use case in a slightly more generic manner.
Fixes #760
Thanks for your help in narrowing this down, @calebboyd, appreciate it.
I’ve tried to adhere to the project conventions as much as possible but please do let me know if you want any changes.
> Adds alternate pre-built Nexe binary remote option (--remote)

- src/patches/third-party-main.ts
Moves the location where nexe boot is included for node 12.18. 
No issue created, but the error was:
```
internal/modules/cjs/loader.js:1078
callbackMap.set(compiled.cacheKey, {
^
TypeError: Cannot read property 'set' of undefined
at wrapSafe (internal/modules/cjs/loader.js:1078:15)
at Module._compile (internal/modules/cjs/loader.js:1102:27)
at internal/bootstrap/pre_execution.js:118:36
at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:119:3)
at internal/main/run_main_module.js:7:1
```
As `callbackMap` is setup later in prepareMainThreadExecution.
Just tested manually against 12.18 - due to the logic this shouldn't affect any other version adversely.
> Move nexe boot to support 12.18.0.

- src/fs/patch.ts
With 12.18.3 (and probably somewhere on master) the return value of internalModuleReadJSON changed to being an array.
No issue raised, the breakage was with package.json loading.
Manually tested against 12.18.3 and 12.18.2 (to test the new and old functionality).
The regex test is to match the check at: https://github.com/nodejs/node/blob/master/src/node_file.cc#L958
> Internal module read json changes

- src/fs/patch.ts
Only generate new date references for faked stat objects. Keeping parent uid/gid and disk info.
cc @OmgImAlexis 
Closes #874 #873
> fix(fs): only override time references

- src/fs/patch.ts
Improve compatibility with the Node fs api,
Adds support for fs-extra v10.
As of https://github.com/jprichardson/node-fs-extra/commit/fb6c0ca16baec6a3f5138685e72cf3659c493017
they no longer conditionally look for these functions.
> Add support fs.realpath(Sync).native.

- README.md
- src/compiler.ts
The asset option was added in 9f22309949bf8207cb9e4566f917d5bdd0324a01 but not added to the README.
Also the error message for remote still referenced "file" even though it was invalid.
Just if of use :-) (I was trawling around and noticed the asset option which is useful for some caching for us.)
> Document the asset option.

- src/options.ts
Changes the options' python description to point to a python3 path instead of python2
Fixes (none that I'm aware of?)
Heyo o/
I found when building my project and compiling node from source (since nexe didn't have the source on its repo?) that it didn't like the python syntax. Something *somewhere* along the line was trying to use the python [f string syntax](https://realpython.com/python-f-strings/), **which is not available in python 2.** I'm not sure if that's something nexe was doing or something in the node build process, but wherever that python call was, changing the python path (via `nexe --python /usr/bin/python3`) fixed it, and it seems to be compiling fine now.
That's …
> Change python2 to python3 in options file

- src/util.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- package-lock.json
- package.json
- src/options.ts
- src/patches/third-party-main.ts
Replaces cherow with meriyah
General dependency bump for npm audit noise.
Closes #985
> refactor: replace cherow with meriyah for parsing es

- src/steps/download.ts
Just makes downloading nodejs output look better
before:
After:
This is not required
> fix: missed space in downloading log line

- src/compiler.ts
After `21.7.3`, `20.12.2` and `18.20.2`, the `Error: spawn EINVAL` started occurring, so I have fixed it.
Fixes #1091 
There are none.
> Fix `Error: spawn EINVAL` on Windows.

- src/patches/disable-node-cli.ts
As of https://github.com/nodejs/node/pull/44746, the function that formerly performed global variable processing changed from `ProcessGlobalArgs` to `ProcessGlobalArgsInternal` with a different return type. This is causing the error seen in https://github.com/nexe/nexe/issues/1084 and https://github.com/nexe/nexe/issues/1082.
Fixes https://github.com/nexe/nexe/issues/1082
Fixes https://github.com/nexe/nexe/issues/1084
> Handle new ProcessGlobalArgsInternal function in node >19

- src/fs/SnapshotZipFS.ts
- test/integration/index.js
Hi @calebboyd,
This is a fix for a compatibility bug in the 5.x branch. In 4.x a file path relative to the current working directory would always be looked up in the nexe binary, and I missed this in the swap to the `/snapshot` path handing in 5.x.
This fixes that, and makes the integration tests run this case too.
I'm moving a bigger app to nexe 5, and this is the main/only blocker I've hit (so far) - so keen to get this landed if possible :-)
Thanks :-)
> Fix file lookup when the nexe binary is in another directory.

- package.json
- src/fs/patch.ts
Node 22 altered the signature for `internaModuleStat` binding, - passing the context as as arg0 and the path as arg1.
This should handle both calls
**Which issue(s) this PR fixes**: 
Fixes # #1119
> fix(node22): handle new arg order
